import type { User, Tenant, Contact, Conversation, Campaign, Workflow, Appointment, DashboardSummary } from '../types';

export const DEMO_CREDENTIALS = {
  email: 'demo@example.com',
  password: 'demo123',
};

export const dummyUser: User = {
  id: 'demo-user-123',
  email: 'demo@example.com',
  first_name: 'Alex',
  last_name: 'Johnson',
  phone: '+1 234 567 8900',
  avatar_url: null,
};

export const dummyTenant: Tenant = {
  id: 'demo-tenant-123',
  name: 'Demo Beauty Salon',
  slug: 'demo-beauty-salon',
  industry: 'Salon & Beauty',
  phone: '+91 98765 43210',
  timezone: 'Asia/Kolkata',
  branding: {
    logo_url: null,
    primary_color: '#667eea',
    secondary_color: '#764ba2',
  },
  onboarding_completed_at: new Date().toISOString(),
  onboarding_step: 2,
  status: 'active',
  created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  updated_at: new Date().toISOString(),
};

export const dummyContacts: Contact[] = [
  {
    id: 'contact-1',
    tenant_id: 'demo-tenant-123',
    first_name: 'Sarah',
    last_name: 'Williams',
    phone: '+91 98765 12345',
    email: 'sarah.williams@example.com',
    avatar_url: null,
    is_lead: true,
    lead_stage: 'qualified',
    source: 'whatsapp',
    notes: 'Interested in hair coloring services',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'contact-2',
    tenant_id: 'demo-tenant-123',
    first_name: 'Michael',
    last_name: 'Chen',
    phone: '+91 98765 23456',
    email: 'michael.chen@example.com',
    avatar_url: null,
    is_lead: true,
    lead_stage: 'contacted',
    source: 'campaign',
    notes: 'Regular customer, prefers weekend appointments',
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'contact-3',
    tenant_id: 'demo-tenant-123',
    first_name: 'Priya',
    last_name: 'Sharma',
    phone: '+91 98765 34567',
    email: 'priya.sharma@example.com',
    avatar_url: null,
    is_lead: false,
    lead_stage: 'converted',
    source: 'whatsapp',
    notes: 'VIP customer, monthly facial appointments',
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'contact-4',
    tenant_id: 'demo-tenant-123',
    first_name: 'David',
    last_name: 'Kumar',
    phone: '+91 98765 45678',
    email: null,
    avatar_url: null,
    is_lead: true,
    lead_stage: 'new',
    source: 'automation',
    notes: null,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'contact-5',
    tenant_id: 'demo-tenant-123',
    first_name: 'Emma',
    last_name: 'Rodriguez',
    phone: '+91 98765 56789',
    email: 'emma.rodriguez@example.com',
    avatar_url: null,
    is_lead: true,
    lead_stage: 'qualified',
    source: 'manual',
    notes: 'Interested in bridal makeup package',
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const dummyConversations: (Conversation & { contact: Contact })[] = [
  {
    id: 'conv-1',
    tenant_id: 'demo-tenant-123',
    contact_id: 'contact-1',
    whatsapp_integration_id: 'wa-123',
    status: 'open',
    assigned_to: null,
    last_message_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    last_message_preview: 'Hi! I would like to book an appointment for hair coloring',
    unread_count: 2,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    contact: dummyContacts[0],
  },
  {
    id: 'conv-2',
    tenant_id: 'demo-tenant-123',
    contact_id: 'contact-2',
    whatsapp_integration_id: 'wa-123',
    status: 'open',
    assigned_to: null,
    last_message_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    last_message_preview: 'Can I reschedule my appointment to next Saturday?',
    unread_count: 1,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    contact: dummyContacts[1],
  },
  {
    id: 'conv-3',
    tenant_id: 'demo-tenant-123',
    contact_id: 'contact-3',
    whatsapp_integration_id: 'wa-123',
    status: 'open',
    assigned_to: null,
    last_message_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    last_message_preview: 'Thank you! The facial was amazing as always',
    unread_count: 0,
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    contact: dummyContacts[2],
  },
  {
    id: 'conv-4',
    tenant_id: 'demo-tenant-123',
    contact_id: 'contact-4',
    whatsapp_integration_id: 'wa-123',
    status: 'open',
    assigned_to: null,
    last_message_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    last_message_preview: 'Hi, what are your prices for haircut?',
    unread_count: 1,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    contact: dummyContacts[3],
  },
];

export const dummyCampaigns: Campaign[] = [
  {
    id: 'campaign-1',
    tenant_id: 'demo-tenant-123',
    name: 'Summer Sale 2024',
    template_id: 'template-1',
    segment_id: 'segment-1',
    status: 'completed',
    scheduled_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    total_recipients: 245,
    sent_count: 245,
    delivered_count: 238,
    read_count: 186,
    replied_count: 42,
    failed_count: 7,
    created_by: 'demo-user-123',
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'campaign-2',
    tenant_id: 'demo-tenant-123',
    name: 'Weekend Bridal Package Promotion',
    template_id: 'template-2',
    segment_id: 'segment-2',
    status: 'processing',
    scheduled_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    completed_at: null,
    total_recipients: 156,
    sent_count: 89,
    delivered_count: 85,
    read_count: 34,
    replied_count: 8,
    failed_count: 4,
    created_by: 'demo-user-123',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'campaign-3',
    tenant_id: 'demo-tenant-123',
    name: 'New Customer Welcome',
    template_id: 'template-3',
    segment_id: 'segment-3',
    status: 'scheduled',
    scheduled_at: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    started_at: null,
    completed_at: null,
    total_recipients: 89,
    sent_count: 0,
    delivered_count: 0,
    read_count: 0,
    replied_count: 0,
    failed_count: 0,
    created_by: 'demo-user-123',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const dummyWorkflows: Workflow[] = [
  {
    id: 'workflow-1',
    tenant_id: 'demo-tenant-123',
    name: 'Welcome Message Auto-Reply',
    description: 'Automatically welcome new customers and provide service information',
    trigger_type: 'keyword',
    trigger_config: { keywords: ['hi', 'hello', 'hey'] },
    nodes: [
      {
        id: 'node-1',
        type: 'send_message',
        config: {
          message: 'Welcome to Demo Beauty Salon! How can we help you today?',
        },
      },
    ],
    status: 'active',
    execution_count: 124,
    created_by: 'demo-user-123',
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'workflow-2',
    tenant_id: 'demo-tenant-123',
    name: 'Appointment Booking Flow',
    description: 'Guide customers through appointment booking process',
    trigger_type: 'keyword',
    trigger_config: { keywords: ['book', 'appointment', 'booking'] },
    nodes: [
      {
        id: 'node-1',
        type: 'send_message',
        config: {
          message: 'Great! I can help you book an appointment. What service are you interested in?',
        },
      },
    ],
    status: 'active',
    execution_count: 87,
    created_by: 'demo-user-123',
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'workflow-3',
    tenant_id: 'demo-tenant-123',
    name: 'Pricing Information',
    description: 'Automatically send pricing details when requested',
    trigger_type: 'keyword',
    trigger_config: { keywords: ['price', 'cost', 'pricing'] },
    nodes: [
      {
        id: 'node-1',
        type: 'send_message',
        config: {
          message: 'Here are our current prices:\n\nHaircut: ₹500\nHair Coloring: ₹2000\nFacial: ₹1500\nMakeup: ₹3000',
        },
      },
    ],
    status: 'active',
    execution_count: 56,
    created_by: 'demo-user-123',
    created_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const dummyAppointments: Appointment[] = [
  {
    id: 'appt-1',
    tenant_id: 'demo-tenant-123',
    contact_id: 'contact-1',
    service_id: 'service-1',
    slot_id: 'slot-1',
    slot_time: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    status: 'confirmed',
    reminder_sent: false,
    notes: 'Hair coloring consultation',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'appt-2',
    tenant_id: 'demo-tenant-123',
    contact_id: 'contact-2',
    service_id: 'service-2',
    slot_id: 'slot-2',
    slot_time: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    status: 'confirmed',
    reminder_sent: false,
    notes: null,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'appt-3',
    tenant_id: 'demo-tenant-123',
    contact_id: 'contact-3',
    service_id: 'service-3',
    slot_id: 'slot-3',
    slot_time: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'confirmed',
    reminder_sent: false,
    notes: 'Monthly facial - VIP customer',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const dummyDashboardSummary: DashboardSummary = {
  new_leads: 12,
  unread_conversations: 4,
  active_campaigns: 1,
  appointments_today: 3,
  automation_responses: 143,
  message_quota_used: 4234,
  message_quota_total: 10000,
};
